name: link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  syncfusion_flutter_datagrid: ^26.1.35
  syncfusion_flutter_gauges: ^26.1.40
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
